---
name: Lint

on:
  push:
    branches:
      - "main"
    paths:
      - "website/**"
  pull_request:
    branches:
      - "**"
    paths:
      - "website/**"

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          sparse-checkout: website

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install Node dependencies
        run: |
          cd website
          npm ci

      - name: Lint
        run: |
          cd website
          npm run lint
